#!/bin/sh

sxhkd &

bspc config focused_border_color "#aa0000"

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

if [[ $(hostname) == 'jmzhang-ld1' ]]; then
    bspc monitor DVI-I-1 -d I II III IV V
    bspc monitor DP-1 -d VI VII VIII IX X
fi

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
