#!/bin/sh

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'

bspc config focused_border_color "#aa0000"

bspc config border_width        2
bspc config window_gap          6
bspc config top_padding         12

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
