#!/bin/sh

bspc config focused_border_color "#55bb33"

bspc config border_width        2
bspc config window_gap          6
bspc config -m ^1 top_padding   25

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config leaf_monocle        true
bspc config focus_by_distance   true

if [[ $(hostname) == 'jmzhang-ld1' ]]; then
    bspc monitor DVI-I-1 -d I II III IV V
    bspc monitor DP-1 -d VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
